development: &development
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: paint_and_sip_dev

test: &test
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: paint_and_sip_test

production: &production
  adapter: mysql2
  host: localhost
  database: paint_and_sip_production
  username: your_production_database_login
  password: your_production_database_password
